// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4mijdojVa2Xhhsyl9bZJtp_vpsPvmAMw',
    appId: '1:279745382016:web:b7111d0caf8f03d77ac865',
    messagingSenderId: '279745382016',
    projectId: 'edr-ticket',
    authDomain: 'edr-ticket.firebaseapp.com',
    storageBucket: 'edr-ticket.firebasestorage.app',
    measurementId: 'G-SK74292K9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC5x9SZcYb7-3oONrRZb36NzfS2usM26I',
    appId: '1:279745382016:android:b8f9a6cbf82bef947ac865',
    messagingSenderId: '279745382016',
    projectId: 'edr-ticket',
    storageBucket: 'edr-ticket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1C6pgZD_xG5DS8-Kd5OeKHpHTB2w7aLU',
    appId: '1:279745382016:ios:56dd3acc3ee0f2347ac865',
    messagingSenderId: '279745382016',
    projectId: 'edr-ticket',
    storageBucket: 'edr-ticket.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4mijdojVa2Xhhsyl9bZJtp_vpsPvmAMw',
    appId: '1:279745382016:web:adbb8f0efddad8137ac865',
    messagingSenderId: '279745382016',
    projectId: 'edr-ticket',
    authDomain: 'edr-ticket.firebaseapp.com',
    storageBucket: 'edr-ticket.firebasestorage.app',
    measurementId: 'G-75QWQXL7JQ',
  );
}
